name: CI - Build and Push Backend Image

on:
  push:
    branches:
      - main

permissions:
  content: read
  package: write

jobs:
  build-and-push:
    name: Build and Push to ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout respository
        uses: action/checkout@v4
      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secret.GITHUB_TOKEN}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/team-app-backend:latest
            ghcr.io/${{ github.repository_owner }}/team-app-backend:${{ github.sha }}